version: '2'
services:
  flask_document_system_mongo:
    image: mongo:4.4
    # build: ./mongo
    container_name: flask_document_system_mongo
    working_dir: /usr/local/work
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    restart: always
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=my_root
      - MONGO_INITDB_ROOT_PASSWORD=my_123456
    command: bash -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && chmod +x /docker-entrypoint-initdb.d/setup.sh"
  
#   flask:
#     build: ./flask
#     links:
#       - mongo
#     ports:
#       - "5000:5000"
#     expose:
#       - "5000"
#     volumes:
#       - ../flask_document_system:/home/web